### ISSUE TITLE
Upgrade Fedora to Fedora 27

### ISSUE THREAD

**Issue by sr229** [gbraad/docker-c9ide#2]
Current image still uses Fedora 25, the current stable Fedora is 27.

**Comment by gbraad** [comment]
Images are built on GitLab and pushed to Docker hub. Latest available is F26, as I usually wait for the first few patches/updates. https://gitlab.com/gbraad/c9ide/container_registry

**Comment by gbraad** [comment]
https://gitlab.com/gbraad/c9ide/container_registry
